#!/bin/bash

set -ex

INSTALL_DIR="`pwd`/_install"
MODULE_PATH="`pwd`/cmake"

source "$INSTALL_DIR/webrtc/VERSIONS"
source "`pwd`/VERSIONS"
SORA_UNITY_SDK_COMMIT = "`git rev-parse HEAD`"

mkdir -p build
pushd build
  cmake .. \
    -DCMAKE_BUILD_TYPE=Release \
    -DSORA_UNITY_SDK_VERSION="$SORA_UNITY_SDK_VERSION" \
    -DSORA_UNITY_SDK_COMMIT="$SORA_UNITY_SDK_COMMIT" \
    -DWEBRTC_VERSION="$WEBRTC_VERSION" \
    -DWEBRTC_READABLE_VERSION="$WEBRTC_READABLE_VERSION" \
    -DWEBRTC_SRC_COMMIT="$WEBRTC_SRC_COMMIT" \
    -DWEBRTC_ROOT_DIR="$INSTALL_DIR/webrtc" \
    -DJSON_ROOT_DIR"=$INSTALL_DIR/json" \
    -DCMAKE_MODULE_PATH="$MODULE_PATH" \
    -DCMAKE_PREFIX_PATH="$INSTALL_DIR/boost"
  cmake --build .
popd
